project:
  type: website
  output-dir: snippets

website:
  title: "snippets"
  twitter-card: true
  opengraph: true
  navbar:
    right:
      - icon: github
        href: https://github.com/fabge/snippets
format:
  html:
    theme:
      light: cosmo
      dark: solar
    highlight-style: github
